browser=chrome
url=https://the-internet.herokuapp.com/login
username=tomsmith
password=SuperSecretPassword!
api.base.url=https://fakestoreapi.com
NaukariUrl=https://www.naukri.com/nlogin/login?URL=https://www.naukri.com/mnjuser/homepage
NaukariUser=piyusha.bansod@gmail.com
NaukariPass=January@2024#



